services:
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
            MYSQL_DATABASE: mariadb
        ports:
            - "3306:3306"
        volumes:
            - maraiadb_data:/var/lib/mysql

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080

volumes:
    maraiadb_data:
